apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sostrades
  namespace: argocd
spec:
  project: sostrades
  source:
    path: deploy/overlays/osc/osc-cl1
    repoURL: https://github.com/operate-first/sostrades.git
    targetRevision: HEAD
  destination:
    name: osc-cl1
    namespace: sostrades
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
